# Generated by Django 2.0.2 on 2019-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mno', models.IntegerField()),
                ('test', models.CharField(choices=[('BLOOD', 'Blood'), ('URINE', 'Urine'), ('GLUCOUSE', 'Glucouse'), ('PREGNANCY', 'Pregnancy')], default='Select', max_length=100)),
                ('amt', models.IntegerField()),
                ('dr', models.CharField(choices=[('DR.KABIR SINGH', 'Dr.Kabir_Singh'), ('DR.AJAY MITTAL', 'Dr.Ajay Mittal'), ('DR.VISHAL PANDE', 'Dr.Vishal Pandy')], default='Select', max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'mood',
            },
        ),
    ]
